hydra:
    run:
        dir: "outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${randid:}"

paths:
    root_dir: "${hydra:runtime.cwd}"
    assets_dir: "${paths.root_dir}/assets"
    outputs_dir: "${hydra:runtime.output_dir}"
    cache_dir: "${paths.outputs_dir}/cache"
    build_dir: "${paths.root_dir}/unity/Builds"

vision:
    model:
        dino_model: "facebook/dinov2-base"
        sam_model: "facebook/sam-vit-base"

    calibrate_camera: true

exp:
    task: "build_truck_supertype"
        # Options: "build_truck_supertype", "build_truck_subtype", "inject_color"
    player_type: "label"
        # Options: "bool", "demo", "label", "full"
    num_episodes: 40

seed: 42